"""Type stubs for the native `kontract._kontract` module."""

from typing import overload

__version__: str
USD: str
EUR: str
GBP: str
JPY: str

class Observable:
    def clip(self, floor: float) -> Observable: ...
    def max(self, other: Observable) -> Observable: ...
    def min(self, other: Observable) -> Observable: ...
    # Observables temporels (J26) : Asian / lookback, style pipeline
    def average(self) -> Observable: ...
    def average_over(self, from_year: float, to_year: float) -> Observable: ...
    def running_max(self) -> Observable: ...
    def running_min(self) -> Observable: ...
    # Style pipeline : obs.add(x).clip(0).scale(contract).when(cond)
    def add(self, other: Observable | float) -> Observable: ...
    def sub(self, other: Observable | float) -> Observable: ...
    def mul(self, other: Observable | float) -> Observable: ...
    def div(self, other: Observable | float) -> Observable: ...
    def scale(self, contract: Contract) -> Contract: ...
    def __add__(self, other: Observable | float) -> Observable: ...
    def __radd__(self, other: Observable | float) -> Observable: ...
    def __sub__(self, other: Observable | float) -> Observable: ...
    def __rsub__(self, other: Observable | float) -> Observable: ...
    def __truediv__(self, other: Observable | float) -> Observable: ...
    def __neg__(self) -> Observable: ...
    @overload
    def __mul__(self, other: Contract) -> Contract: ...
    @overload
    def __mul__(self, other: Observable | float) -> Observable: ...
    def __rmul__(self, other: Observable | float) -> Observable: ...
    def __ge__(self, other: Observable | float) -> Condition: ...
    def __gt__(self, other: Observable | float) -> Condition: ...
    def __le__(self, other: Observable | float) -> Condition: ...
    def __lt__(self, other: Observable | float) -> Condition: ...

class Condition:
    def __and__(self, other: Condition) -> Condition: ...
    def __or__(self, other: Condition) -> Condition: ...
    def __invert__(self) -> Condition: ...

class Contract:
    def __matmul__(self, cond: Condition) -> Contract: ...
    def __add__(self, other: Contract) -> Contract: ...
    def __neg__(self) -> Contract: ...
    def until(self, cond: Condition) -> Contract: ...
    def anytime(self, cond: Condition) -> Contract: ...
    def or_(self, other: Contract) -> Contract: ...
    def to_json(self) -> str: ...
    @staticmethod
    def from_json(s: str) -> Contract: ...
    def price(
        self,
        model: GBM | Model,
        n_paths: int = ...,
        seed: int = ...,
        steps_per_year: int = ...,
        antithetic: bool = ...,
        control_variate: bool = ...,
    ) -> PriceResult: ...
    def price_american(
        self,
        model: GBM | Model,
        exercise_dates: list[float],
        n_paths: int = ...,
        seed: int = ...,
        n_basis: int = ...,
    ) -> PriceResult: ...
    def price_under_rates(
        self,
        rate_model: RateModel,
        n_paths: int = ...,
        seed: int = ...,
        steps_per_year: int = ...,
    ) -> PriceResult: ...
    def greeks(
        self,
        model: GBM,
        n_paths: int = ...,
        seed: int = ...,
        steps_per_year: int = ...,
    ) -> Greeks: ...

class GBM:
    asset: str
    s0: float
    sigma: float
    r: float
    q: float
    def __init__(
        self, s0: float, sigma: float, r: float, q: float = ..., asset: str = ...
    ) -> None: ...

class Model: ...

class GbmFactor:
    def __init__(self, name: str, s0: float, mu: float, sigma: float) -> None: ...

class RateModel:
    def zero_bond(self, t: float, big_t: float, r_t: float) -> float: ...
    def discount_bond0(self, big_t: float) -> float: ...

class Swaption:
    @staticmethod
    def level(
        expiry: float, tenor: float, n: int, fixed_rate: float, is_payer: bool = ...
    ) -> Swaption: ...

class PriceResult:
    price: float
    std_error: float
    sample_std: float
    ci95_low: float
    ci95_high: float
    n_paths: int

class Greeks:
    price: float
    delta: float
    gamma: float
    vega: float
    rho: float

def zero() -> Contract: ...
def one(ccy: str) -> Contract: ...
def give(c: Contract) -> Contract: ...
def S(name: str) -> Observable: ...
def spot(name: str) -> Observable: ...
def const_(x: float) -> Observable: ...
def at(t: float) -> Condition: ...

# Observables temporels (J26)
def average(obs: Observable) -> Observable: ...
def average_over(obs: Observable, from_year: float, to_year: float) -> Observable: ...
def running_max(obs: Observable) -> Observable: ...
def running_min(obs: Observable) -> Observable: ...

# Simulateur multi-actifs corrélé (J27)
def correlated_gbm(
    factors: list[GbmFactor], corr: list[list[float]], r: float
) -> Model: ...

# Modèles
def heston(
    spot: float,
    v0: float,
    kappa: float,
    theta: float,
    sigma_v: float,
    rho: float,
    r: float,
    asset: str = ...,
) -> Model: ...
def sabr(
    spot: float, alpha: float, beta: float, nu: float, rho: float, r: float, asset: str = ...
) -> Model: ...
def merton(
    spot: float,
    r: float,
    sigma: float,
    lambda_: float,
    mu_j: float,
    sigma_j: float,
    asset: str = ...,
) -> Model: ...
def rough_bergomi(
    spot: float, v0: float, xi: float, h: float, rho: float, r: float, asset: str = ...
) -> Model: ...
def sobol_gbm(spot: float, sigma: float, r: float, q: float = ..., asset: str = ...) -> Model: ...

# Taux
def vasicek(r0: float, a: float, b: float, sigma: float) -> RateModel: ...
def hull_white(r0: float, a: float, sigma: float) -> RateModel: ...
def swaption_mc(
    rate_model: RateModel,
    swaption: Swaption,
    n_paths: int = ...,
    seed: int = ...,
    steps: int = ...,
) -> PriceResult: ...
def vasicek_swaption_analytic(
    r0: float, a: float, b: float, sigma: float, swaption: Swaption
) -> float: ...

# Produits
def zero_coupon_bond(ccy: str, t: float) -> Contract: ...
def european_call(asset: str, k: float, t: float, ccy: str) -> Contract: ...
def european_put(asset: str, k: float, t: float, ccy: str) -> Contract: ...
def forward(asset: str, k: float, t: float, ccy: str) -> Contract: ...
def straddle(asset: str, k: float, t: float, ccy: str) -> Contract: ...
def bull_call_spread(
    asset: str, k_low: float, k_high: float, t: float, ccy: str
) -> Contract: ...
def cash_or_nothing_call(
    asset: str, k: float, payout: float, t: float, ccy: str
) -> Contract: ...
def up_and_out_call(asset: str, k: float, barrier: float, t: float, ccy: str) -> Contract: ...
def down_and_out_call(asset: str, k: float, barrier: float, t: float, ccy: str) -> Contract: ...

# FX
def garman_kohlhagen_call(
    x0: float, k: float, t: float, r_d: float, r_f: float, sigma: float
) -> float: ...
def garman_kohlhagen_put(
    x0: float, k: float, t: float, r_d: float, r_f: float, sigma: float
) -> float: ...
def fx_forward(x0: float, t: float, r_d: float, r_f: float) -> float: ...
def quanto_call(
    s0: float,
    k: float,
    t: float,
    r_d: float,
    r_f: float,
    q_s: float,
    sigma_s: float,
    sigma_x: float,
    rho: float,
) -> float: ...

# Calibration / données de marché
def implied_volatility(
    call_price: float,
    spot: float,
    strike: float,
    maturity: float,
    rate: float,
    dividend_yield: float,
) -> float: ...
def fit_gbm_volatility(
    contract: Contract,
    maturities: list[float],
    market_prices: list[tuple[float, float]],
    rate: float,
    n_paths: int = ...,
) -> float: ...
